steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "iso_bootstrap", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["run", "--name", "iso_bootstrap", "--privileged", "iso_bootstrap", "chroot", "/srv/fai/nfsroot", "/build.sh"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["commit", "-m", "chroot init", "--change", "CMD ['fai-cd', '-fMJd', ', '-g', '/etc/fai/grub.cfg', '/workspace/ethjar.iso']", "iso_bootstrap", "eu.gcr.io/$PROJECT_ID/ethjar:live"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["run", "--privileged", "eu.gcr.io/ethjar-store/ethjar:live"]
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', '/workspace/ethjar.iso', 'gs://ethjar-store/iso/ethjar-$REVISION_ID.iso']

timeout: 1h
images: ["eu.gcr.io/$PROJECT_ID/ethjar:live"]
