steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "eu.gcr.io/$PROJECT_ID/debian:bootstrap", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["run", "--name", "ethjar_bootstrap", "--privileged", "eu.gcr.io/$PROJECT_ID/debian:bootstrap"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["commit", "-m", "chroot init", "ethjar_bootstrap", "eu.gcr.io/$PROJECT_ID/debian:chroot"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["run", "-v", "/workspace:/workspace", "--rm", "--privileged", "--entrypoint", "/root/live_boot/mkusb.sh", "eu.gcr.io/$PROJECT_ID/debian:chroot"]
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', '/workspace/image/disk.img', 'gs://ethjar-store/iso/debian-linux-ethjar-amd64-$REVISION_ID.img']

timeout: 3600s
images: ["eu.gcr.io/$PROJECT_ID/debian:bootstrap", "eu.gcr.io/$PROJECT_ID/debian:chroot"]
